### ISSUE TITLE
Is there a way so that clicking on the link will open a new wikipedia tab?

### ISSUE THREAD

**Issue by antoninadert** [AnandChowdhary/hovercard#1]
Is it possible to have it as an option or do we have to manually add the link to wikipedia for each hovercard?

I suspect it is already on the roadmap just wanted to confirm.

Is it the `Support for cards linking to article/other things`

**Comment by AnandChowdhary** [comment]
Yep, that's the plan! Linking to the article or a custom link will be added soon. :)

**Comment by AnandChowdhary** [comment]
Hi @antoninadert, this has been added in 1.2.0. You can now do this to make the hovercard link to the respective Wikipedia article:

```js
new Hovercard({
    link: "wikipedia"
});
```

You can also do this to make the hovercard link to its reference's link:

```html
<a href="https://google.com" class="hovercard">Google</a>
```

```js
new Hovercard({
    link: "inherit"
});
```

Finally, you can also supply a custom link:

```html
<span data-link="https://google.com" class="hovercard">Google</span>
```

I hope this is good for now! 😄
